---
- name: Set data groupe
  hosts: all
  connection: local

  
  tasks:
  - set_fact:
      a: "{{all_monitor}}"
  - set_fact:
      a: "{{ a.split('and ') }}"
  - set_fact:
      c: "{{monitor}}"
  - set_fact:
      c: "{{a + [c] }}"
    when: '"Geen monitor gevonden" not in a'

  - debug: var=c

  - name: Set a monitor 
    bigip_pool:
      state: present
      name: "{{name_pool}}"
      partition: "{{partition}}"
      monitors: "{{c}}"        
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost

