---
- name: Set data groupe
  hosts: all
  connection: local
  
  tasks: 

  - name: Create a data group of IP addresses from a file
    bigip_data_group:
      name: "{{data_groupe}}"
      partition: "{{partition}}"
      records:
        - key: "{{key}}"
          value: "{{value}}"
      type: address
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost