---
- name: Set data groupe
  hosts: all
  connection: local

  
  tasks:
  - set_fact:
      string: Geen monitor gevonden
      a: "{{all_monitor}}"

  - set_fact:
      a: "{{ a.split('and ') }}"
      when: 'string != a'

  - debug: var=a

  - set_fact:
      c: "{{monitor}}"
  - set_fact:
      b: "{{a + [c] }}"

  - debug: var=b

  - name: Set a monitor 
    bigip_pool:
      state: present
      name: "{{name_pool}}"
      partition: "{{partition}}"
      monitors: "{{b}}"        
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost

