---
- name: Set data groupe
  hosts: all
  connection: local
  
  tasks: 
  - name: add new record to 
    bigip_command: # 1 ssl profile moet defould sni hebben 
      commands: modify internal "{{data_groupe}}" records [add] {"{{key}}" { data ["{{value}}"] } }
      chdir: "{{partition}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost