---
- name: Delete data groupe
  hosts: all
  connection: local
  
  tasks: 
  - name: add new record to data griyoe
    bigip_command: 
      commands: delete ltm data-group internal "{{data_groupe}}"
      chdir: "{{partition}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost