---
- name: delete memberschip
  hosts: all
  connection: local

  vars:
  var1: {{  member.split(":") | lower }}
  var2: {{  member.split(":") | higher }}

  tasks:   
  - name: delete memberschip
    bigip_pool_member:
      pool: "{{pool_name}}"
      partition: "{{partition}}"
      host: "{{var1}}"
      port: "{{var2}}"
      state: absent
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost