---
- name: delete memberschip
  hosts: all
  connection: local

  tasks:   
  - set_fact:
      var1: "{{member.split(':')[0]}}"
      var2: "{{member.split(':')[1]}}"

  - name: delete memberschip
    bigip_pool_member:
      pool: "{{pool_name}}"
      partition: "{{partition}}"
      host: "{{var1}}"
      port: "{{var2}}"
      state: absent
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost