---
- name: delete irule
  hosts: all
  connection: local

 
  tasks:
  - name: delete the iRule fo the LTM module
    bigip_irule:
      module: ltm
      name: "{{irule_name}}"
      partition: "{{partition}}"
      state: absent 
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
