---
- name: F5_create_member_add_to_pool
  hosts: all
  connection: local
 
  tasks:
  - name: Add node
    bigip_node:
      partition: "{{partition}}"
      host: "{{ip}}"
      name: "{{ip}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost

  - name: Add pool member
    bigip_pool_member:
      pool: "{{pool_name}}"
      partition: "{{partition}}"
      host: "{{ip}}"
      name: "{{ip}}"
      port: 443
      description: "{{description}}" 
      connection_limit: 100
      rate_limit: 50
      ratio: 2
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost

    