---
- name: F5 create a pool
  hosts: all
  connection: local
 
  tasks:
  - name: Create pool
    bigip_pool:
      state: present
      name: "{{pool_name}}"
      partition: "{{partition}}"
      lb_method: round-robin
      # monitors:
      #   - https_443
      slow_ramp_time: 120
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
  