---
- name: upload ssl cert
  hosts: all
  connection: local
  gather_facts: no

  tasks: 

  - name: Import PEM Certificate
    bigip_ssl_certificate:
      name: "{{name_ssl}}"
      state: present
      content: "{{lookup('file', {{name_ssl}}) }}"
      partition: "{{partition}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
