---
- name: upload ssl cert
  hosts: all
  connection: local
  gather_facts: no

  tasks: 
  - debug: msg="{{lookup('file', '/lib_core/tls-ca-bundle.pem') }}"

  - name: Import PEM Certificate
    bigip_ssl_certificate:
      name: tls-ca-bundle.pem
      state: present
      content: "{{lookup('file', '/lib_core/tls-ca-bundle.pem') }}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
