---
- name: gather facts Big IP
  hosts: all
  connection: local
  src: https://github.com/f5devcentral/ansible-role-f5ansible 
  
 
  
  
  tasks:
  - name: Collect all BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - ltm-pools
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    

          


