---
- name: gather facts Big IP
  hosts: all
  connection: local
  
  
  tasks:
#  - name: Collect all BIG-IP facts
#    bigip_device_facts:
#      gather_subset:
#        - pools
#      provider:
#        server_port: 443
#        server: 192.168.201.251
#        validate_certs: no
#    delegate_to: localhost
    
  - name: Get pool facts
    bigip_gtm_facts:
      include: pool
      filter: my_pool
    delegate_to: localhost
          


#fsgsfagsfd


