---
- name: gather facts Big IP
  hosts: all
  connection: local
 
  roles:
    - role: f5devcentral.f5ansible
  
  tasks:
  - name: Collect all BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - all
      provider:
        config: "{{ lookup('file', '/tmp/f5job.xml') }}"
        user: {{f5_username}}
        password: {{f5_password}}
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    

          


