---
- name: gather facts Big IP
  hosts: all
  connection: local
 
  roles:
    - role: f5devcentral.f5ansible
  
  tasks:
  - name: Collect all BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - all
    delegate_to: localhost
    

          


