---
- name: gather facts Big IP
  hosts: all
  connection: local
  
  tasks:
  - name: Collect all BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - all
      provider:
        
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    

          


