---
- name: gather facts Big IP
  hosts: all
  connection: local
  roles:
    - role: f5devcentral.bigip_to_ansible
      bigip_to_ansible_qkview: /path/to/localhost.localdomain.qkview
 
  
  
  tasks:
  - name: Collect all BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - ltm-pools
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    

          


