---
- name: gather facts Big IP
  hosts: all
 
  roles:
    - role: f5devcentral.f5ansible
  
  tasks:
  - name: Collect all BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - all
      provider:
        server_port: 443
        validate_certs: no 
    delegate_to: localhost
    

          


