---
- name: Create new partition and logging profiles
  hosts: all
  connection: local

  tasks:
    - name: Create group with delete protection enabled and custom attributes
      win_domain_group:
        name: "{{groupename}}"
        scope: domainlocal
        category: security
        organizational_unit: "OU=F5_partitions,OU=Hosting,DC=tesis,DC=corp"
        domain_username: "{{username}}"
        domain_password: "{{password}}"
        domain_server: tAD901.tesis.corp
