---
- name: Create new partition and logging profiles
  hosts: all
  gather_facts: no

  tasks:
    - set_fact:
        groupname: "{{partition}}"

    - name: Create group with delete protection enabled and custom attributes
      win_domain_group: 
        name: "ptn_{{groupname}}"
        scope: global
        category: security
        organizational_unit: "OU=F5_partitions,OU=ManagedIQ,OU=Hosting,DC=tesis,DC=corp"
        domain_server: tAD901.tesis.corp
        domain_username: "{{ADusername}}"
        domain_password: "{{ADpassword}}"

    - name: Add a domain group to a domain group
      win_domain_group_membership:
        name: "ptn_{{groupname}}"
        members:
          - "{{MIQgroupe}}"
        state: present

    - name: Add a domain group to a domain group
      win_domain_group_membership:
        name: "ptn_{{groupname}}"
        members:
          - "manage_iq_admins"
        state: present