---
- name: Create new partition and logging profiles
  hosts: all
  gather_facts: no


  tasks:
    - name: Create group with delete protection enabled and custom attributes
      win_domain_group: 
        name: "{{groupename}}"
        scope: domainlocal
        category: security
        organizational_unit: "OU=F5_partitions,OU=ManagedIQ,OU=Hosting,DC=tesis,DC=corp"
        domain_server: tAD901.tesis.corp
        domain_username: "{{ADusername}}"
        domain_password: "{{ADpassword}}"

    - name: Add a domain group to a domain group
      win_domain_group_membership:
        name: "{{MIQgroupe}}"
        members:
          - "{{groupename}}"
        state: present