---
- name: new irule
  hosts: all
  connection: local

  tasks: 
  - copy: content="{{irule_code}}" dest=/tmp/{{irule_name}}.tlc

  - name: new the iRule to the LTM module
    bigip_irule:
      module: ltm
      name: "{{irule_name}}"
      src: "/tmp/{{irule_name}}.tlc"
      partition: "{{partition}}"
      state: present 
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
