---
- name: New node
  hosts: all
  connection: local
 
  tasks:
  - name: Add node
    bigip_node:
      partition: "{{partition}}"
      host: "{{ip}}"
      name: "{{ip}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost