---
- name: Create new partition and logging profiles
  hosts: all
  connection: local

  tasks:
    - set_fact:
        i: "{{partition}}"
        ptn: "ptn_"
        l: "$"
           
    - name: Create names
      set_fact:
        k: "{{ptn}}{{i}}"
        v: "rlog_{{i}}_defauld_http"
        template1: "{{l}}BIGIP_HOSTNAME cloud Request client={{l}}CLIENT_IP:{{l}}CLIENT_PORT vip={{l}}VIRTUAL_IP:{{l}}VIRTUAL_PORT pool={{l}}VIRTUAL_POOL_NAME snat={{l}}SNAT_IP:{{l}}SNAT_PORT server={{l}}SERVER_IP:{{l}}SERVER_PORT site={{l}}{Host} path={{l}}HTTP_PATH request={{l}}HTTP_REQUEST UserAgent={{l}}{User-agent} vs={{l}}VIRTUAL_NAME status={{l}}HTTP_STATUS time-taken={{l}}RESPONSE_MSECS sc-bytes={{l}}RESPONSE_SIZE via={{l}}"
        template2: "{{l}}BIGIP_HOSTNAME cloud Response client={{l}}CLIENT_IP:{{l}}CLIENT_PORT vip={{l}}VIRTUAL_IP:{{l}}VIRTUAL_PORT pool={{l}}VIRTUAL_POOL_NAME snat={{l}}SNAT_IP:{{l}}SNAT_PORT server={{l}}SERVER_IP:{{l}}SERVER_PORT site={{l}}{Host} path={{l}}HTTP_PATH request={{l}}HTTP_REQUEST UserAgent={{l}}{User-agent} vs={{l}}VIRTUAL_NAME status={{l}}HTTP_STATUS time-taken={{l}}RESPONSE_MSECS sc-bytes={{l}}RESPONSE_SIZE via={{l}}{Via}"
      

    # - name: Create partition
    #   bigip_partition:
    #     name: "{{k}}"
    #     provider:
    #       server_port: 443
    #       server: 192.168.201.251
    #       validate_certs: no
    #   delegate_to: localhost

    # - name: add new logging request porfile
    #   bigip_command: # 1 ssl profile moet defould sni hebben
    #    commands:  create ltm profile request-log "{{v}}" defaults-from /Common/rlog_default # maak een template request logging aan voor dat dit werkt
    #    chdir: "{{k}}"
    #    provider:
    #      server_port: 443
    #      server: 192.168.201.251
    #      validate_certs: no
    #   delegate_to: localhost

    # - name: mod loggin request
    #   bigip_command: # 1 ssl profile moet defould sni hebben #request-logging
    #    commands:  modify ltm profile request-log '{{v}}' response-logging enabled
    #    chdir: "{{k}}"
    #    provider:
    #      server_port: 443
    #      server: 192.168.201.251
    #      validate_certs: no
    #   delegate_to: localhost

    - name: mod loggin request
      bigip_command: # 1 ssl profile moet defould sni hebben response-logging enabled response-log-template ['{{template2}}']
        commands: modify ltm profile request-log {{v}} response-log-template "{{template2}}"
        chdir: "{{k}}"
        provider:
          server_port: 443
          server: 192.168.201.251
          validate_certs: no
      delegate_to: localhost
      ignore_errors: yes
