
---
- name: virtual server remove SSL
  hosts: all
  connection: local

  tasks: 
    - set_fact:
        i: "{{partition}}"
        discription: jaja
        ptn: 'ptn_'
        rlog: 'rlog_'
        def: '_defauld_tcp'
    - set_fact:
        k: "{{ptn}}--{{i}}"

    - set_fact:
        v: "{{rlog_}}--{{i}}--{{def}}"  

    - name: Create partition 
      bigip_partition:
        name: "{{k}}"
        description: "{{discription}}"
        provider:
          server_port: 443
          server: 192.168.201.251
          validate_certs: no
      delegate_to: localhost

    - name: add new logging request porfile
      bigip_command: # 1 ssl profile moet defould sni hebben 
       commands:  create request-log ["{{v}}"] defaults-from Common/request-log # maak een template request logging aan voor dat dit werkt  
       chdir: "{{k}}"
       provider:
         server_port: 443
         server: 192.168.201.251
         validate_certs: no
      delegate_to: localhost

    - name: mod loggin request 
      bigip_command: # 1 ssl profile moet defould sni hebben 
       commands:  modify request-log ["{{v}}"] request-log-template $BIGIP_HOSTNAME cloud Request client=$CLIENT_IP:$CLIENT_PORT vip=$VIRTUAL_IP:$VIRTUAL_PORT pool=$VIRTUAL_POOL_NAME snat=$SNAT_IP:$SNAT_PORT server=$SERVER_IP:$SERVER_PORT site=${Host} path=$HTTP_PATH request=$HTTP_REQUEST UserAgent=${User-agent} vs=$VIRTUAL_NAME status=$HTTP_STATUS time-taken=$RESPONSE_MSECS sc-bytes=$RESPONSE_SIZE via=${Via}
       chdir: "{{k}}"
       provider:
         server_port: 443
         server: 192.168.201.251
         validate_certs: no
      delegate_to: localhost

    - name: mod loggin request 
      bigip_command: # 1 ssl profile moet defould sni hebben 
       commands:  modify request-log ["{{v}}"] response-log-template $BIGIP_HOSTNAME cloud Response client=$CLIENT_IP:$CLIENT_PORT vip=$VIRTUAL_IP:$VIRTUAL_PORT pool=$VIRTUAL_POOL_NAME snat=$SNAT_IP:$SNAT_PORT server=$SERVER_IP:$SERVER_PORT site=${Host} path=$HTTP_PATH request=$HTTP_REQUEST UserAgent=${User-agent} vs=$VIRTUAL_NAME status=$HTTP_STATUS time-taken=$RESPONSE_MSECS sc-bytes=$RESPONSE_SIZE via=${Via}
       chdir: "{{k}}"
       provider:
         server_port: 443
         server: 192.168.201.251
         validate_certs: no
      delegate_to: localhost