---
- name: New data groupe
  hosts: all
  connection: local

  tasks: 
  - copy: content="{{data_groupe_data}}" dest=/tmp/data_groupe.txt

  - name: Create a data group of IP addresses from a file
    bigip_data_group:
      name: "{{data_groupe}}"
      partition: "{{partition}}"
      records_src: /tmp/data_groupe.txt
      type: address
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost