---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - copy: content="{{irule_code}}" dest=/tmp/irule.tlc

  - name: update the iRule to the LTM module
    bigip_irule:
      module: ltm
      name: "{{irule_name}}"
      src: "/tmp/irule.tlc"
      partition: "{{partition}}"
      state: present 
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
