---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - set_fact:
      i: "{{client_ssl}}"
      v: "{{name_server}}"

  - name: add new ssh profile 
    bigip_command:
      commands: mod ltm virtual "{{v}}" profiles add { "{{i}}" { context clientside } 
      chdir: "{{partition}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost



   

