---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - name: add Irule virtual server
    bigip_virtual_server:
      partition: "{{partition}}"
      name: "{{name_server}}"
      irules: "{{name_irule}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    when: '"{{name_irule}}"is defined and ("{{name_irule}}"|length>0)'


   