---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - set_fact:
      arr1: "{{name_irule}}"
      arr2: "{{irule_array}}"
      irule:  "{{arr1 + arr2}}"

  - name: add Irule virtual server
    bigip_virtual_server:
      partition: "{{partition}}"
      name: "{{name_server}}"
      irules: "{{irule}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    when: '"{{irule}}"is defined and ("{{irule}}"|length>0)'


   