---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - set_fact:
      x: "{{ irule_array.split(':') }}"
      i: "{{name_irule}}"

  - set_fact:
      z: "{{ x + [ i ] }}"    

  - name: add Irule virtual server
    bigip_virtual_server:
      partition: "{{partition}}"
      name: "{{name_server}}"
      irules: "{{z}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    when: '"{{z}}"is defined and ("{{z}}"|length>0)'


   