---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - set_fact:
      val1: "{{ irule_array.split(':') }}"
      val2: "{{name_irule}}"
      val3: "{{val1 + [ val2 ] }}"



  - name: add Irule virtual server
    bigip_virtual_server:
      partition: "{{partition}}"
      name: "{{name_server}}"
      irules: "{{arry}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    when: '"{{arry}}"is defined and ("{{arry}}"|length>0)'


   