---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - set_fact:
      x: "{{ array_profiles.split(':') }}"
      i: "{{client_ssl}}"

  - debug: var=x
  - debug: var=i
      

  - set_fact:
      v: "{{ x + [ i ] }}"

  - debug: var=v

  - name: add SSH client profile virtual server
    bigip_virtual_server:
      partition: "{{partition}}"
      name: "{{name_server}}"
      profiles: "{{v}}"
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
    when: '"{{v}}"is defined and ("{{v}}"|length>0)'

  - name: add SSH client profile virtual server
    bigip_virtual_server:
      partition: "{{partition}}"
      name: "{{name_server}}"
      profiles: 
        - name: tcp-mobile-optimized
          context: client-side
        - name: tcp-lan-optimized
          context: server-side
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
   

