---
- name: virtual server
  hosts: all
  connection: local

  tasks: 
  - name: Add the iRule contained in template irule.tcl to the LTM module
    bigip_irule:
      module: ltm
      name: "{{irule_name}}"
      src: "{{irule_code}}"
      partition: "{{partition}}"
      state: present 
      provider:
        server_port: 443
        server: 192.168.201.251
        validate_certs: no
    delegate_to: localhost
