---
- name: Set request and response template 
  hosts: all
  connection: local  
  gather_facts: yes

  tasks:
    - set_fact:
        src_address_id:     "{{src_address.split(',')[0]}}"
        src_address_name:   "{{src_address.split(',')[1]}}"
        des_address_id:     "{{des_address.split(',')[0]}}"
        des_address_name:   "{{des_address.split(',')[1]}}"
    - set_fact:
        src_address_id:     "{{ src_address_id | int }}"
        des_address_id:     "{{ des_address_id | int }}"
        fw_group_int:       "{{ fw_group | int }}"
        

    - set_fact:    
        frule: '{ "rule": {
                    "app-fw-policy": {},
                    "rule-group-type": "CUSTOM",
                    "utm-policy": {},
                    "ips-policy": {},
                    "rule-profile": {
                        "profile-type": "USER_DEFINED",
                        "user-defined-profile": {
                            "id": 65856,
                            "name": "All Logging Enabled"
                        },
                        "custom-profile": {
                            "web-redirect": false,
                            "tcp-syn-check": false,
                            "infranet-redirect": "NONE",
                            "destination-address-translation": "NONE",
                            "redirect": "NONE",
                            "web-redirect-to-https": false,
                            "authentication-type": "NONE",
                            "service-offload": false,
                            "tcp-seq-check": false,
                            "window-scale-check": false,
                            "push-to-jims": false
                        }
                    },
                    "rule-order": 5,
                    "ips-enabled": false,
                    "policy-id": 983122,
                    "destination-address": {
                        "exclude-list": false,
                        "addresses": {
                            "address-reference": [
                                {
                                    "id": {{des_address_id}},
                                    "uuid": {{des_address_id}},
                                    "name": "{{des_address_name}}"
                                }
                            ]
                        }
                    },
                    "version": 7,
                    "rule-type": "RULE",
                    "vpn-tunnel-refs": {},
                    "disabled": false,
                    "rulegroup-disabled": false,
                    "hit-count-details": {},
                    "edit-version": 2,
                    "rule-group-id": {{fw_group_int}},
                    "scheduler": {},
                    "services": {
                        "service-reference": [
                            {
                                "id": 164015,
                                "is-group": false
                            }
                        ]
                    },
                    "action": "PERMIT",
                    "threat-policy": {},
                    "condition-actions": {},
                    "custom-column-data": "",
                    "description": "",
                    "sourceidentities": {},
                    "destination-zone": {
                        "zone": [
                            {
                                "zone-type": "ZONE",
                                "resolved": false,
                                "name": "{{des_zone}}",
                                "variable-id": 0
                            }
                        ]
                    },
                    "name": "{{fw_name}}",
                    "source-zone": {
                        "zone": [
                            {
                                "zone-type": "ZONE",
                                "resolved": false,
                                "name": "{{src_zone}}",
                                "variable-id": 0
                            }
                        ]
                    },
                    "ssl-forward-proxy-profile": {},
                    "machine-identity": {},
                    "dynamic-application-profile": {},
                    "source-address": {
                        "exclude-list": false,
                        "addresses": {
                            "address-reference": [
                                {
                                    "id": {{src_address_id}},
                                    "uuid": {{src_address_id}},
                                    "name": "{{src_address_name}}"
                                }
                            ]
                        }
                    }   
                }
            }'
  

    - set_fact:
    #  frule: "{{frule | to_json}}"
        Content_Type: "application/vnd.juniper.sd.policy-management.firewall.rule+json;version=2;charset=UTF-8"

    - debug: var=frule        
    - copy: content="{{frule}}" dest=/tmp/frule_tmp.json
       

    - name: API call junos space add new rule
      uri:
        url: https://192.168.201.31/api/juniper/sd/policy-management/firewall/policies/983122/rules
        method: POST
        src: /tmp/frule_tmp.json
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no
        headers:
          Content-Type: "{{Content_Type}}"

