---
- name: Update and publish SRX policy  
  hosts: all
  connection: local  
  gather_facts: yes

  tasks:
    - set_fact:
         reg: '{
    "publish": {
        "delete-oldest-snapshot": "false",
        "policy-ids": {
            "policy-id": "983122"
        }
    }
}'
     
    - debug: var=req

    - set_fact:
        req: "{{ req | to_json }}"
        Content_Type: "application/vnd.juniper.sd.fwpolicy-provisioning.publish+json;version=1;charset=UTF-8"

    - copy: content="{{req}}" dest=/tmp/req101.json

    - name: API call junos space publis policy 
      uri:
        url: https://192.168.201.31/api/juniper/sd/policy-management/firewall/provisioning/publish-policy?update=true
        method: POST
        return_content: yes
        headers:
          Content-Type: "{{Content_Type}}"
        src: /tmp/req101.json
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no

          