---
- name: Update and publish SRX policy  
  hosts: all
  connection: local  
  gather_facts: no

  tasks:
    - set_fact:
         req105:   '{  "service" : {    
                          "protocols" : {      
                              "protocol" : [ {        
                                  "sunrpc-protocol-type" :  "{{protecol}}" ,        
                                  "msrpc-protocol-type" :  "{{protecol}}",    
                                  "protocol-number": 6,
                                  "name": "{{name_service}}",            
                                  "dst-port" : {{port_number}},
                                  "disable-timeout" : false,
                                  "inactivity-timeout" : "300",        
                                  "protocol-type" :  "PROTOCOL_{{protecol}}"        
                                  } ]    
                              },        
                              "name" : "{{name_service}}",
                              "is-group" : false,
                              "description" : "toegevoegd via ManageIQ",    
                              "members" : { }
                          }
                      }'
     
    - debug: var=req105

    - set_fact:
        Content_Type: "application/vnd.juniper.sd.service-management.service+json;version=1;charset=UTF-8"

    - copy: content="{{req105}}" dest=/tmp/req105.json

    - name: API call junos space publis policy 
      uri:
        url: https://192.168.201.31/api/juniper/sd/policy-management/firewall/provisioning/publish-policy?update=true
        method: POST
        header:
          Content-Type: "{{Content_Type}}"
        return_content: yes
        src: /tmp/req105.json
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no
