---
- name: delete firewall rule 
  hosts: all
  connection: local  
  gather_facts: no

  tasks:
    - set_fact:
        url: https://192.168.201.31/api/juniper/sd/policy-management/firewall/policies/983122/rules/{{firewall_rule}}

    - name: API call junos space delete firewall rule 
      uri:
        url: "{{url}}"
        method: DELETE
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no
