---
- name: Create new address SRX 
  hosts: all
  connection: local  
  gather_facts: yes

  tasks:
    - set_fact:
         Content_Type: "application/vnd.juniper.sd.address-management.address+json;version=1;charset=UTF-8"
         req102:   '{  "address" : {    
                          "name": "{{name_addres}}",
                          "address-type": "{{address_type}}",
                          "ip-address": "{{address}}",
                          "description": "",
                          "host-name": "",
                          "definition-type": "CUSTOM",
                          "domain-id": 2,
                          "domain-name": "Global"
                          }
                      }'
     
    - debug: var=req102

    - copy: content="{{req102}}" dest=/tmp/req102.json

    - name: Add address 
      uri:
        url: https://192.168.201.31/api/juniper/sd/address-management/addresses
        method: POST
        return_content: yes
        headers:
          Content-Type: "{{Content_Type}}"
        src: /tmp/req102.json
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no

