---
- name: New service 
  hosts: all
  connection: local  
  gather_facts: no

  tasks:
    - set_fact:
         req20: '{  "service": {    
                        "protocols": {      
                          "protocol":  {        
                             "sunrpc-protocol-type":  "{{protecol}}" ,        
                                "msrpc-protocol-type":  "{{protecol}}",    
                                "protocol-number": "6",
                                "name": "{{name_service}}",            
                                "dst-port": "{{port_number}}",
                                "disable-timeout": "false",
                                "inactivity-timeout": "300",        
                                "protocol-type":  "PROTOCOL_{{protecol}}"        
                                }     
                            },        
                            "name": "{{name_service}}",
                            "is-group": "false",
                            "description": "toegevoegd via ManageIQ",    
                            "members": {}
                         } 
                    }'
     
    - debug: var=req105

    - copy: content="{{req20}}" dest=/tmp/req20.json

    - name: New Service
      uri:
        url: https://192.168.201.31/api/juniper/sd/service-management/services
        method: POST
        header:
          Content-Type: "application/vnd.juniper.sd.service-management.service+json;version=1;charset=UTF-8"
        return_content: yes
        src: /tmp/req20.json
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no
