---
- name: Update and publish SRX policy  
  hosts: all
  connection: local  
  gather_facts: no

  tasks:
    - set_fact:
        update: '{ "publish" : {
                      "policy-ids" : {
                        "policy-id" : "983122"
                        },
                      "delete-oldest-snapshot" : "false"  
                     }
                   }'
        
        # Accept_Type: "application/vnd.juniper.sd.fwpolicy-provisioning.monitorable-task-instances+json;version=1;q=0.01"

    - debug: var=update
    - set_fact:
        update: "{{ update | to_json }}"
        Content_Type_U: "application/vnd.juniper.sd.fwpolicy-provisioning.publish+json;version=1;charset=UTF-8"

    - copy: content="{{update}}" dest=/tmp/update_tmp

    - pause:
        seconds: 10 

    - name: API call junos space publis policy 
      uri:
        url: "https://192.168.201.31/api/juniper/sd/policy-management/firewall/provisioning/publish-policy?update=true"
        method: put
        src: /tmp/update_tmp
        password: "{{ADpassword}}"
        user: "{{ADusername}}"
        validate_certs: no
        force_basic_auth: yes
        use_proxy: no
        headers:
          Content-Type: "{{Content_Type_U}}"
          